name: CI/CD Pipeline

# This triggers the workflow whenever you push code to the 'main' branch.
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # This specifies the environment for running the job

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Step to checkout your code from the repository

    - name: Log in to AWS ECR
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
      # This logs GitHub Actions into AWS ECR using your credentials

    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/crypto-price-service:latest .
      # This step builds your Docker image using the Dockerfile in the repository

    - name: Push to ECR
      run: |
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/crypto-price-service:latest
      # This step pushes the newly built Docker image to AWS ECR
